# Main netlify.toml - Choose which app to deploy as primary
# Currently disabled to avoid conflicts with individual app deployments
# Uncomment and modify the base path below to deploy a specific app as primary

# [build]
#   base = "Arxiv/angular-search-app"
#   command = "npm run build"
#   publish = "dist/angular-search-app"

# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# [build.environment]
#   NODE_VERSION = "18"
