# Netlify configuration for Svelte arXiv search app
[build]
  base = "Arxiv/svelte-search-app"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
