# Netlify configuration for Svelte SimpleZon Dropdown App
[build]
  base = "Dropdown/svelte-dropdown-app"
  command = "npm install && npm run build"
  publish = "dist"

# SPA redirect rules for Svelte
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
